default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  secure_auth: false
  database: blog3_db
  username: mack
  password: mack
  host: localhost

development:
  <<: *default

testing:
  <<: *default

production:
  <<: *default


